### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by ronsavage** [poti1/tiny-prof#1]
(1) 
In the Synopsis a tiny nit:
# the builds the results page.
should read:
# then builds the results page.
(2)
Under Stage 1: Setup Environment:
sudo vi /etc/systemdsystem/MY_SERVICE.service
should read (on my Debian box at least):
sudo vi /etc/systemd/system/MY_SERVICE.service

**Comment by poti1** [comment]
Thanks for the feedback. I just fixed these.
